library identifier: 'jenkins-pipeline-demo-library@master', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/prasad-deepu/jenkins-pipeline-demo-library.git'])

pipeline {
    agent any
    stages {
        stage('Audit tools') {                        
            steps {
                auditTools2 message: 'This is demo 2' + ' '+'and it\'s build number is: '+ "${BUILD_NUMBER}"
            }
        }
    }
}
