library identifier: 'jenkins-pipeline-demo-library@master', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/prasad-deepu/jenkins-pipeline-demo-library.git'])

pipeline {
        agent {label 'slave_dotnet' }
    stages {
        stage('Audit tools') {                        
            steps {
                auditTools()
            }
        }
    }
}
